#!/bin/bash
if [ "$#" -ne 4 ]; then
    echo Usage : $0 ' <Config File #(1~16)> <# of banks> <# of clients each bank> <# of banks whose clients run>'
    exit
fi

pkill server
pkill master
pkill client
rm -f ../logs/*
if [ $1 -lt 10 ]; then
    N="0$1"
    echo $N
else
    N="$1"
fi
for i in `seq 0 $[$2-1]`; do
    for j in `seq $[(4+$i)*1000+1] $[(4+$i)*1000+4]`; do
        go run server/server.go $j config$N.json &
    done
done
echo servers launched!
sleep 2
#gnome-terminal -e "go run master/master.go config$N.json"
go run master/master.go config$N.json &
echo master launched!
ctr=0
for i in `seq 0 $[$2-1]`; do
    if [ $ctr -lt $4 ]; then
        for j in `seq 0 $[$3-1]`; do 
            PORT=$[(4+$i)*1000+999-$j]
            echo $PORT
#           gnome-terminal -e "go run client/client.go $PORT config$N.json"
            go run client/client.go $PORT config$N.json &
        done
    fi
    ctr=$[$ctr+1]
done
#go run client/client.go 4999 config$N.json &
echo clients launched!
